source 'https://github.com/puyang0521/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'podTextProject_Example' do
  pod 'podTextProject', :path => '../'

  target 'podTextProject_Tests' do
    inherit! :search_paths

    
  end
end
